language: python

dist: xenial

matrix:
  include:
    - python: 3.6
      env: TOX_ENV='flake8'
    - python: 3.6
      env: TOX_ENV='isort'
    - python: 3.6
      env: TOX_ENV='docs'
    - python: 3.6
      env: TOX_ENV='frontend'
    # Django 2.2
    - python: 3.5
      env: DJANGO='dj22' SWAP='swap'
    - python: 3.6
      env: DJANGO='dj22' SWAP='noswap'
    - python: 3.7
      env: DJANGO='dj22' SWAP='swap'
    - python: 3.8
      env: DJANGO='dj22' SWAP='noswap'
    # Django 3.0, always run the lowest supported version
    - python: 3.6
      env: DJANGO='dj30' SWAP='swap'
    - python: 3.6
      env: DJANGO='dj30' SWAP='noswap'
    # Django 3.1, always run the lowest supported version
    - python: 3.6
      env: DJANGO='dj31' SWAP='swap'
    - python: 3.6
      env: DJANGO='dj31' SWAP='noswap'
  allow_failures:
    - python: 3.6
      env: DJANGO='dj31' SWAP='swap'
    - python: 3.6
      env: DJANGO='dj31' SWAP='noswap'

install:
  - pip install coverage isort tox
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then export PY_VER=py35; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then export PY_VER=py36; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then export PY_VER=py37; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]; then export PY_VER=py38; fi"
  - "if [[ ${DJANGO}z != 'z' ]]; then export TOX_ENV=$PY_VER-$DJANGO-$SWAP; fi"

before_script:
  - if [ $TOX_ENV == 'frontend' ]; then
    pip install -r tests/requirements/frontend.txt;
    nvm install 0.12.7 && nvm use 0.12.7;
    npm config set spin false;
    npm install -g npm@2;
    npm install -g gulp@3.9.0;
    npm install;
    fi

script:
  - tox -e $TOX_ENV

after_success:
  - bash <(curl -s https://codecov.io/bash)
