name: CodeCov

on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
        requirements-file: [
          django-3.2.txt,
          django-4.0.txt,
          django-4.1.txt,
          django-4.2.txt,
          django-5.0.txt,
        ]
        custom-image-model: [false, true]
        exclude:
          - requirements-file: django-5.0.txt
            python-version: 3.8
          - requirements-file: django-5.0.txt
            python-version: 3.9
        os: [
          ubuntu-20.04,
        ]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: library prerequisites
      run: sudo apt-get install python-dev libpq-dev libmagic1 gcc libxml2-dev libxslt1-dev libjpeg62 libopenjp2-7 -y
    - name: Install extra dependencies
      run: pip install lxml
      if: matrix.python-version == '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tests/requirements/${{ matrix.requirements-file }}
        python setup.py install
    - name: Enable the custom image model
      run: echo "CUSTOM_IMAGE=custom_image.Image" >> $GITHUB_ENV
      if: ${{ matrix.custom-image-model }}
    - name: Run coverage
      run: coverage run setup.py test
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1
